pipeline {
    agent {
        node {
            label 'AGENT-1'
        }
    }

    environment {
        PATH = "/bin:/usr/bin:/usr/local/bin"
    }

    options {
        timeout(time: 60, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    stages {

        stage('Init') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            /bin/terraform version
                            /bin/terraform init
                        """
                    }
                }
            }
        }

        stage('Plan') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            /bin/terraform plan
                        """
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                        sh """
                            /bin/terraform apply -auto-approve
                        """
                    }
                }
            }
        }

        stage('Trigger SG') {
            steps {
                script {
                    build job: '10-sg',
                        wait: false,
                        propagate: false
                }
            }
        }
    }

    post {
        always {
            echo 'I will always say Hello again!'
            cleanWs()
        }

        success {
            echo 'I will run if success'
        }

        failure {
            echo 'I will run if failure'
        }

        aborted {
            echo 'pipeline is aborted'
        }
    }
}